import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 4}
dynamic_padding = true

[font]
normal = { family="JetBrainsMono Nerd Font", style="Regular"}
